language: python
matrix:
  include:
  - name: linux_py3
    python: 3.7
    os: linux
    before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
  - name: macosx_py3
    os: osx
    osx_image: xcode11.3
    language: shell
    before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
  - name: win_py3
    os: windows
    language: shell
    before_install:
    #git clone --depth=50 --branch=dev https://github.com/fastlmm/FaST-LMM.git fastlmm/FaST-LMM
    #cd fastlmm/FaST-LMM
    - choco install miniconda3
    - echo $ChocolateyToolsLocation
    - export SYSP=/c/tools/miniconda3
    - export PATH=$SYSP:$SYSP/Library/bin:$SYSP/Scripts:$PATH

install:
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda install pip
- conda install "mkl==2019.4" "scipy>=1.1.0" "numpy>=1.11.3"
#python -m pip install --extra-index-url https://test.pypi.org/simple/ --index-url https://pypi.org/simple/ 'fastlmm'
#- pip install fastlmm
#- pip install git+https://github.com/fastlmm/PySnpTools.git@dev
- pip install pysnptools

script:
- python pysnptools.minitest.py

notifications:
  email:
    recipients:
    - carlk@msn.com
    on_success: always
    on_failure: always
