name: CI
on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-13, macOS-14]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v3

    - name: Install Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Create a virtual environment
      run: uv venv

    - name: Activate, and use virtual environment
      shell: bash
      run: |
        if [[ "$RUNNER_OS" != "Windows" ]]; then
          source .venv/bin/activate
        else
          source .venv/Scripts/activate
        fi
        uv pip install pysnptools[bgen]==0.5.14 # a1 --prerelease=allow
        uv pip install fastlmm==0.6.12 # a1 --prerelease=allow
        
        # Run tests
        python bed-reader.minitest.py
        python pysnptools.minitest.py
        python fastlmm.minitest.py
