name: CI
on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.8, 3.7, 3.9, "3.10"]
        exclude:
            - os: windows-latest
              python-version: "3.10"
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Miniconda ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

    - name: Install Prerequisites and build
      shell: bash -l {0}
      run: |
        #conda install pip
        conda install "mkl==2019.4" "scipy" "numpy"
        #pip install --no-build-isolation --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple bed-reader==0.2.24
        #pip install bed-reader==0.2.23
        #pip install pysnptools==0.5.2
        pip install --no-build-isolation --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pysnptools
        #pip install --no-build-isolation fastlmm
        #pip install cbgen==1.0.1
        #pip install fastlmm
        #pip install --no-build-isolation --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple fastlmm
        #pip install --no-build-isolation --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple fastlmm==0.6.1
        

    - name: Test
      shell: bash -l {0}
      run: |
        python bed-reader.minitest.py
        python pysnptools.minitest.py
        #python fastlmm.minitest.py
        
        
